version: '3'
services:
# REACT
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./react/dist:/app/dist
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - api

  # GOLANG
  api:
    build:
      context: .
      dockerfile: ./go/Dockerfile
    volumes:
      - ./go:/app/
    ports:
      - "8090:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
 
  # MYSSQL DATABASE
  mysql:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: '112w4nka'
      MYSQL_ROOT_HOST: "%"
    ports: 
      - '8036:3306'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./database/mysql:/var/lib/mysql
